[tool.poetry]
name = "finalproject_Romanov_M25-555"
version = "0.1.0"
description = "Project 3 python MEPhI Course"
authors = ["Mikhail Romanov <miroshama@gmail.com>"]
readme = "README.md"
packages = [
    { include = "valutatrade_hub", from = "." }
]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.5"
python-dotenv = "^1.2.1"

[tool.poetry.scripts]
project = "main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.14.10,<0.15.0)"
]

[tool.valutatrade]
rates_ttl_seconds = 600
default_base_currency = "EUR"
data_directory = "data"