[tool.poetry]
name = "finalproject-romanov-m25-555"
version = "0.1.0"
description = "Project 3 python MEPhI Course"
authors = ["Mikhail Romanov <miroshama@gmail.com>"]
readme = "README.md"
packages = [
    { include = "valutatrade_hub", from = "." }
]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
project = "main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.14.10,<0.15.0)"
]
